# Generated by Django 5.2.17 on 2026-09-20 04:16

import budget.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='Teresa', max_length=80)),
                ('title', models.CharField(default='Everyday budget', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reserve', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start', models.DateField(default=budget.models.period_start)),
                ('end', models.DateField(default=budget.models.period_end)),
            ],
        ),
        migrations.CreateModel(
            name='SpendingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(default='Other', max_length=40)),
                ('date', models.DateField(default=datetime.date.today)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
