# Generated by Django 5.2.17 on 2026-09-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('kind', models.CharField(choices=[('actual', 'Actual'), ('theoretical', 'Theoretical')], max_length=11, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['actual', 'theoretical'])), name='only_two_plan_slots')],
            },
        ),
    ]
